# Generated by Django 5.1.2 on 2024-10-13 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('biography', models.TextField(verbose_name='Biografía')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('foundation_date', models.DateField(verbose_name='Fecha de fundación')),
                ('address', models.TextField(verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('pages', models.IntegerField(verbose_name='Páginas')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Portada')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Autores')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.publisher', verbose_name='Editora')),
            ],
        ),
    ]
