# Generated by Django 5.1.2 on 2024-10-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Portada'),
        ),
    ]
